### ISSUE TITLE
running on macos

### ISSUE THREAD

**Issue by pseudozach** [nbd-wtf/cliche#1]
I'm trying to run this on macos because I need to test lntxbot and looks like there's dependency.

I get below error:
`java -jar -Dcliche.datadir="/Users/z/.cliche" -Dcliche.seed="xxx" cliche.jar`  

>Exception in thread "main" java.lang.ExceptionInInitializerError
        at Main$.init(Main.scala:77)
        at Main$.<clinit>(Main.scala:361)
        at Main.main(Main.scala)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at fr.acinq.secp256k1.Secp256k1JvmKt.tryLoad(Secp256k1Jvm.kt:26)
        at fr.acinq.secp256k1.Secp256k1JvmKt.getSecpk256k1(Secp256k1Jvm.kt:34)
        at fr.acinq.bitcoin.Crypto$.nativeSecp256k1$lzycompute(Crypto.scala:40)
        at fr.acinq.bitcoin.Crypto$.fr$acinq$bitcoin$Crypto$$nativeSecp256k1(Crypto.scala:39)
        at fr.acinq.bitcoin.Crypto$PrivateKey.add(Crypto.scala:52)
        at fr.acinq.bitcoin.DeterministicWallet$.derivePrivateKey(DeterministicWallet.scala:244)
        at fr.acinq.bitcoin.DeterministicWallet$.$anonfun$derivePrivateKey$1(DeterministicWallet.scala:301)
        at fr.acinq.bitcoin.DeterministicWallet$.$anonfun$derivePrivateKey$1$adapted(DeterministicWallet.scala:301)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at fr.acinq.bitcoin.DeterministicWallet$.derivePrivateKey(DeterministicWallet.scala:301)
        at immortan.LightningNodeKeys$.makeFromSeed(LightningNodeKeys.scala:16)
        at immortan.WalletSecret.<init>(LNParams.scala:486)
        at DB$.<clinit>(DB.scala:9)
        ... 3 more
Caused by: java.lang.IllegalStateException: No native library found: at /fr/acinq/secp256k1/jni/native/darwin-aarch64/libsecp256k1-jni.dylib
        at fr.acinq.secp256k1.jni.NativeSecp256k1JvmLoader.loadSecp256k1NativeLibrary(NativeSecp256k1JvmLoader.kt:203)
        at fr.acinq.secp256k1.jni.NativeSecp256k1JvmLoader.load(NativeSecp256k1JvmLoader.kt:34)
        ... 22 more

**Comment by fiatjaf** [comment]
Unfortunately we need https://github.com/ACINQ/secp256k1-kmp/issues/54 to be solved before it can run on arm64 MacOS.

**Comment by pseudozach** [comment]
Looks like there's a workaround (https://github.com/ACINQ/eclair/issues/2427#issuecomment-1271083222), I'll try it but otherwise we'll be stuck waiting for GitHub to support M1 VMs.

Or I'll just use a gitpod instance to build and debug.

**Comment by fiatjaf** [comment]
Or you build and I'll deploy it to prod to test there.

**Comment by rorp** [comment]
Or you can use this trick: https://github.com/rorp/snostr#to-apple-silicon-users
